user:
  name: syed

aws:
  region: us-east-1

  source_bucket: noaa-global-hourly-pds
  source_raw_prefix: ""

  project_bucket: syed-datsbd-s2026

  bronze_prefix: bronze/isd
  silver_prefix: silver/weather
  gold_prefix: gold/wind
  models_prefix: models
  forecasts_prefix: forecasts
  benchmarks_prefix: benchmarks

runtime:
  local_data_root: /home/ubuntu/data
  local_output_root: /home/ubuntu/renewable-energy-forecasting-pipeline/outputs

ec2:
  spark_master_url: spark://172.31.80.104:7077 # NOT PERMANENT
  ssh_host: ec2-44-204-68-235.compute-1.amazonaws.com
  ssh_user: ubuntu
